name: CI Android

on:
  workflow_dispatch:
  push:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11.0.3
      - name: Build with Gradle
        run: ./gradlew build
