name: update-deps
on:
  schedule:
    - cron:  '0 12 * * *'

jobs:
  spokestack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: reviewdog/action-depup@v1
        id: update-deps
        with:
          file: versions.properties
          version_name: spokestack_version
          repo: spokestack/spokestack-android

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update ${{ steps.update-deps.outputs.repo }} to ${{ steps.update-deps.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.update-deps.outputs.repo }} to ${{ steps.update-deps.outputs.latest }}"
          body: |
            Update ${{ steps.update-deps.outputs.repo }} to [${{ steps.update-deps.outputs.latest }}](https://github.com/${{ steps.update-deps.outputs.repo }}/releases/tag/spokestack-android${{ steps.update-deps.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          labels: "skip-changelog"
          branch: depup-${{ steps.update-deps.outputs.repo }}
